### ISSUE TITLE
Top level domain listed in domains.txt not recognized on query

### ISSUE THREAD

**Issue by JozeMarkic** [microsoft/idfix#11] opened 2020-04-06 15:51 UTC
### Category
- [ ] Enhancement
- [x] Bug
- [ ] Question
- [ ] Documentation gap/issue

### Version

Please specify what version of IdFix you are using: [latest: 2.0.0.0 ]

### Expected / Desired Behavior / Question
Old version of IdFix (1.08) works ok with top level domain ".si"

### Observed Behavior
Attributes on all objects using top level domain ".si" are marked as error.

### Steps to Reproduce
Tested with UPN and proxy address attributes.

**Comment by patrick-rodgers** [comment] 2020-04-06 17:39
Hmm, not sure. The domains are definitely read from the resource file (domains.txt). Can you provide any additional context?

Also, out of curiosity can you try the very latest version published today if you haven't already (2.1.3.0)? Version should be visible in the title bar.

Will have a look at see if I can find a problem. Thanks for letting us know.

**Comment by JozeMarkic** [comment] 2020-04-07 10:04
I laso tried the latest version and it has the same problem... A friend of mine tested it in his environment with .com domain and he also has this problem. He tried it with few customers and they can't get it to work in any environment tested.

**Comment by CedTrafimet** [comment] 2020-04-07 16:33
Maybe same issue for me too. Version 2.1.3.0. Tried on a .com domain (let's say contoso.com) and almost all AD user's UPN and proxyAddresses attributes are marked with topleveldomain error. 
The funny thing is that the proposed update value is the same.

**Comment by FrankCarius** [comment] 2020-04-07 16:40
Same Problem with 2.1.3.0. nearly every UPN is marked as "topleveldomain"-Error. I cloned the Source to find out the root cause (I'm "only" a Powershell Coder)
form1.cs line 125 contains a 
using (StreamReader reader = new StreamReader(Assembly.GetExecutingAssembly().GetManifestResourceStream("IdFix.domains.txt")))

I searched for that reference but did not find it as a string.
But i was able to find a "domains.txt"  beneath  "IDFix"-Application.  Maybe it is only that small type, that the string contains "IdFix" and should be "domains.txt" instead ?

**Comment by jcnengel** [comment] 2020-04-08 20:35
Sounds about right, funny thing is for us that a dot before the "@" is removed in the suggested UPN.

**Comment by patrick-rodgers** [comment] 2020-04-10 19:21
Great work Frank, appreciate you doing some debugging. Will have a look at getting this fixed and a new version out early next week.

**Comment by patrick-rodgers** [comment] 2020-04-20 12:58
I haven't been able to duplicate this issue yet, but please see [the update on](https://github.com/microsoft/idfix/issues/14) our efforts to refactor the code.

**Comment by pedro-roeseler** [comment] 2020-04-21 07:37
> Maybe same issue for me too. Version 2.1.3.0. Tried on a .com domain (let's say contoso.com) and almost all AD user's UPN and proxyAddresses attributes are marked with topleveldomain error.
> The funny thing is that the proposed update value is the same.

Same issue here. Almost everything marked with topleveldomain error.

**Comment by 91jme** [comment] 2020-04-22 12:02
Just wanted to add that we're seeing the same issue in version 2.1.3.0 downloaded today.

".co.uk" is not recognised as a valid TLD, due to the index-shift on 1699 of Form1.cs. This results in a lookup of "uk" in domains.txt, which contains all TLDs but prefixed with ".".

1699 should have the "+ 1" index shift removed so that the tldDomain value matches that of the TLDs listed in domains.txt.

**Comment by patrick-rodgers** [comment] 2020-04-22 17:47
Thanks all, will chase this one down as part of the refactoring tracked by #14.

**Comment by disiku** [comment] 2020-04-23 23:13
Tested v2.0.0.0 - v2.1.3.0 - All of them list every .com domain. Tested old v1.09 without the issue. Same system, same domain.

**Comment by patrick-rodgers** [comment] 2020-04-24 19:02
Have this one fixed now in the refactored code. Still looking for folks to help test a beta version, please comment on issue #14 to let us know if you are interested.

**Comment by patrick-rodgers** [comment] 2020-04-30 16:33
This will go out in the 2.2.0.0 release, closing the issues as fixed. Thanks!

**Closed by patrick-rodgers** 2020-04-30 16:33 UTC
Labels: bug, fixed / complete
